import "./globals.css";

import type { Metadata } from "next";
import { Poppins } from "next/font/google";

import { cn } from "@/utils/cn";

const font = Poppins({
    subsets: ["latin"],
    weight: ["200", "300", "400", "500", "600", "700", "800", "900"]
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html suppressHydrationWarning className="flex justify-center max-w-screen overflow-x-hidden" lang="en">
            <body
                className={cn("w-full overflow-x-hidden xl:!overflow-visible", font.className)}
                style={{ overflow: "visible" }}
            >
                <div className="text-primary flex flex-col items-center justify-between">
                    {children}
                </div>
            </body>
        </html>
    );
}